name: Update Dune Cache

on:
  schedule:
    - cron: "25 0 * * *"  # هر روز ساعت 00:25 UTC
  workflow_dispatch:  # امکان اجرای دستی از پنل GitHub

jobs:
  update-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: ./scripts

      - name: Fetch data from Dune & update cache
        run: node ./scripts/update-dune-cache.js
        working-directory: ./scripts
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}

      - name: Check if file changed
        run: |
          echo "---- Diff Output ----"
          git diff data/DB.json || echo "No changes in DB.json detected"
          if [ -z "$(git diff data/DB.json)" ]; then
            echo "No changes detected in DB.json. Skipping commit."
          fi

      - name: Commit & push updated cache
        run: |
          # اگر تغییرات جدیدی وجود دارد، commit و push می‌کنیم
          if [ -n "$(git diff data/DB.json)" ]; then
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add data/DB.json
            git commit -m "Update Dune cache [auto]" || echo "No changes to commit"
            git push
          else
            echo "No changes to commit. Skipping push."
          fi
